# config/packages/acseo_typesense.yml
# acseo_typesense:
#     # Typesense host settings
#     typesense:
#         url: '%env(resolve:TYPESENSE_URL)%'
#         key: '%env(resolve:TYPESENSE_KEY)%'
#         collection_prefix: 'test_'                 # Optional : add prefix to all collection 
#                                                    #            names in Typesense
#     # Collection settings
#     collections:
#         foods:                                     # Typesense collection name
#             entity: 'App\Entity\Food'              # Doctrine Entity class
#             fields: 
#                 #
#                 # Keeping Database and Typesense synchronized with ids
#                 #
#                 id:                                # Entity attribute name
#                     name: id                       # Typesense attribute name
#                     type: primary                  # Attribute type
#                 #
#                 # Using again id as a sortable field (int32 required)
#                 #
#                 sortable_id:
#                     entity_attribute: id             # Entity attribute name forced
#                     name: sortable_id                # Typesense field name
#                     type: int32
#                 name: 
#                     name: name
#                     type: string
#             default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float