doctrine:
    dbal: 
        url: '%env(DATABASE_URL)%' # IMPORTANT: You MUST configure your server version, # either here or in the DATABASE_URL env var (see .env file) 
        # driver: 'pdo_pgsql'
        # server_version: '16'
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8 
        mapping_types:
            status_enum: string

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
