twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true

when@dev:
    twig:
        globals:
            username: Florent from when@dev
        





