controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr: ''
        en: '/en'
        es: '/es'

kernel:
    resource: ../../src/Kernel.php
    type: annotation


