connect_google:
    path: /connect/google
    controller: App\Controller\SecurityController::connectGoogle

connect_google_check:
    path: /connect/google/check

connect_github:
    path: /connect/github
    controller: App\Controller\SecurityController::connectGithub

connect_github_check:
    path: /connect/github/check
